### ISSUE TITLE
How to have access image topic on GO1

### ISSUE THREAD

**Issue by am-amani** [ngmor/unitree_inspection#2]
Hi..

I am working with ROS 1 on GO1 EDU version. My robot is only publishing point cloud data, but no other topic related to image! Can you help me how I can have access to image topic?

Thank you for your attention.

**Comment by ngmor** [comment]
You may have to ssh into the Jetson Nanos to start the camera nodes, I'm not sure if those nodes started by default or not. This project was done in ROS 2, so unfortunately I didn't do too much troubleshooting in ROS 1, and I don't have a lot of experience with using ROS 1 with the Go1.
